version: '3'

services:
    reverse-proxy:
        image: traefik:v2.3
        command: 
            #- "--log.level=DEBUG"
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.websecure.address=:443"
            - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
            #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
            - "--certificatesresolvers.myresolver.acme.email=cloud@spilikin.dev"
            - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
        ports:
            # The HTTP port
            - "443:443"
            # The Web UI (enabled by --api.insecure=true)
            - "8080:8080"
        volumes:
            # So that Traefik can listen to the Docker events
            - /var/run/docker.sock:/var/run/docker.sock
            - "./.letsencrypt:/letsencrypt"
    
    spegg-api:
        build:
            context: https://github.com/spilikin/spegg.git
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.api.rule=Host(`api.spegg.spilikin.dev`)"
            - "traefik.http.routers.api.entrypoints=websecure"
            - "traefik.http.routers.api.tls.certresolver=myresolver"

    # vansu-service:
    #     build:
    #         context: https://github.com/spilikin/vansu-service.git
    #     labels:
    #         - "traefik.enable=true"
    #         - "traefik.http.routers.api.rule=Host(`api.globex.spilikin.dev`)"
    #         - "traefik.http.routers.api.entrypoints=websecure"
    #         - "traefik.http.routers.api.tls.certresolver=myresolver"
    # vansu-vue:
    #     build:
    #         context: https://github.com/spilikin/vansu-vue.git#staging
    #     labels:
    #         - "traefik.enable=true"
    #         - "traefik.http.routers.vue.rule=Host(`globex.spilikin.dev`)"
    #         - "traefik.http.routers.vue.entrypoints=websecure"
    #         - "traefik.http.routers.vue.tls.certresolver=myresolver"
            