version: '3.1'

services:
    mongo:
        image: bitnami/mongodb:latest
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
            MONGODB_USERNAME: spegg
            MONGODB_PASSWORD: bad_password
            MONGODB_DATABASE: spegg

        ports: 
            - "27017-27019:27017-27019"
        