[tool.poetry]
name = "spegg"
version = "0.1.0"
description = ""
authors = ["Spilikin"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.24.0"
pydantic = "^1.6.1"
PyYAML = "^5.3.1"
openpyxl = "^3.0.5"
pymongo = "^3.11.0"
fastapi = "^0.61.1"
uvicorn = "^0.12.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
db_test = "spegg.db:test"
db_clean = "spegg.db:clean"
convert = "spegg.converter:convert_data"
serve = "spegg.api:serve"